{{- if .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Chart.Name | trimSuffix "-chart" | trunc 44 }}-controller-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-rds-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-rds-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-rds-controller.chart.name-version" . }}
{{- with .Values.metrics.prometheusRule.additionalLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  groups:
    - name: {{ include "ack-rds-controller.app.name" . }}
      rules:
{{- with .Values.metrics.prometheusRule.rules }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}

