---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-rds-reader
  namespace: default
rules:
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbsecuritygroups
  - dbsubnetgroups
  verbs:
  - get
  - list
  - watch
