---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-rds-writer
  namespace: default
rules:
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters
  - dbclusterendpoints
  - dbclusterparametergroups
  - dbclustersnapshots
  - dbinstances
  - dbparametergroups
  - dbproxies
  - dbsnapshots
  - dbsubnetgroups
  - globalclusters
  - optiongroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rds.services.k8s.aws
  resources:
  - dbclusters
  - dbclusterendpoints
  - dbclusterparametergroups
  - dbclustersnapshots
  - dbinstances
  - dbparametergroups
  - dbproxies
  - dbsnapshots
  - dbsubnetgroups
  - globalclusters
  - optiongroups
  verbs:
  - get
  - patch
  - update
