apiVersion: v1
name: rds-chart
description: A Helm chart for the ACK service controller for Amazon Relational Database Service (RDS)
version: 1.1.9
appVersion: 1.1.9
home: https://github.com/aws-controllers-k8s/rds-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/rds-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: RDS Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/rds-maintainer
keywords:
  - aws
  - kubernetes
  - rds
